import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

import { site, radio, sid, ltd, lou, juso } from './rad'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {

    fetch(`${site}?${radio}&${sid}&${ltd}&${lou}&${juso}`)
      .then((res) => console.log(res))
      .catch((err) => console.log(err))

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          asdf
        </div>
      </main>
    </>
  )
}
